apiVersion: v1
kind: Secret
metadata:
  name: mysql-secret
type: Opaque
data:
  username: a3ljLWdhdGV3YXk=
  password: a2ozZnI2NzNnOGRoamYwMjloODc=
  database: a3ljLWdhdGV3YXk=
  root-password: ODdmZzc2MjNyOGg5ajAzOTLDnzBodHI2
