apiVersion: v1
data:
  OAUTH_BASE_URL: >-
    https://keycloak.test.k8s.i-lab.online/auth/realms/ilab/protocol/openid-connect
  OAUTH_CLIENT_ID: kyc
  OAUTH_CLIENT_SECRET: 578ace75-c47f-4605-8e72-f59cc2dd004f

kind: ConfigMap
metadata:
  name: bankingholidays-service
---
apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  labels:
    name: bankingholidays-service
  name: bankingholidays-service
spec:
  maxReplicas: 3
  minReplicas: 2
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: bankingholidays-service
  targetCPUUtilizationPercentage: 90
---
kind: Deployment
apiVersion: extensions/v1beta1
metadata:
  name: bankingholidays-service
spec:
  replicas: 1
  template:
    metadata:
      labels:
        name: bankingholidays-service
    spec:
      hostname: bankingholidays-service
      containers:
        - name: kyc-gateway
          image: docker.pkg.github.com/nordlb/banking-holidays-service/banking-holidays-service:latest
          ports:
            - containerPort: 8080
          env:
            - name: spring_profiles_active
              value: kubernetes
            - name: MYSQL_HOST
              value: mariadb
            - name: MYSQL_USERNAME
              valueFrom:
                secretKeyRef:
                  name: mysql-secret
                  key: username
            - name: MYSQL_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: mysql-secret
                  key: password
            - name: MYSQL_DATABASE
              valueFrom:
                secretKeyRef:
                  name: mysql-secret
                  key: database
          #          readinessProbe:
          #            failureThreshold: 100
          #            httpGet:
          #              path: /actuator/health
          #              port: 8080
          #              scheme: HTTP
          #            initialDelaySeconds: 30
          #            periodSeconds: 10
          #            successThreshold: 1
          #            timeoutSeconds: 1
          envFrom:
            - configMapRef:
                name: bankingholidays-service
          resources:
            requests:
              cpu: 200m
              memory: 350Mi
            limits:
              cpu: 400m
              memory: 500Mi

---
apiVersion: v1
kind: Service
metadata:
  labels:
    name: bankingholidays-service
  name: bankingholidays-service
spec:
  ports:
    - port: 80
      targetPort: 8080
      protocol: TCP
      name: http
  selector:
    name: bankingholidays-service
